# Generated by Django 6.0.3 on 2026-03-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"ordering": ["id"]},
        ),
    ]
